apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-sm
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - auth-service
  selector:
    matchLabels:
      app: auth-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s